language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-24
    - android-24
    - sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-24
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
