language: android
jdk:
  - oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-24
    - sys-img-x86-android-24
  licenses:
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
